
--select c.g,c.s from c



insert into refer (
COD_REFER, COD_SEGMTO, COD_GRUPO, COD_SUBGRUPO, COD_REFER_FORNEC, DESCRICAO,          COMPLEMENTO_DESCRICAO,  UNIDADE_MEDIDA_ENTD, UNIDADE_MEDIDA, FATOR_CONV_UNIDADE_MEDIDA, DT_INCLUSAO,            DT_CANCELAMENTO, DT_INI_BLOQUEIO,   DT_FIM_BLOQUEIO,   PRECO_CUSTO,                                     PRECO_CUSTO_ANT1, PRECO_CUSTO_ANT2, DT_PRECO_CUSTO, DT_CUSTO_ANT1,  DT_CUSTO_ANT2, PRECO_VENDA,                                                 ALIQUOTA_IPI, ESTOQUE_MINIMO, ESTOQUE_ATUAL, ESTOQUE_PENDENTE, ESTOQUE_PENDENTE_VENDA, ESTOQUE_FISCAL, ESTOQUE_SEC1, ESTOQUE_SEC2, PESO_LIQUIDO, PESO_BRUTO, COMISSAO_VENDA, MARGEM_LUCRO, COEFICIENTE_VENDA,                                                                                           DESPESAS_OPERACIONAIS, ICMS_SUBST, STATUS, COMISSAO_CUSTO, DESCONTO_LIMITADO, DESCONTO_MAXIMO, PRECO_VENDA_ANT1, DT_PRECO_VENDA, DT_VENDA_ANT1, ICMS_VENDA, IMPOSTO_FIXO, ORIGEM_INC, LARGURA_TECIDO, RENDIMENTO_TECIDO, DT_EXPIRACAO, DESCRICAO_CLASSE, COD_GRADE1, COD_GRADE2, COD_GRADE3, DESCRICAO_REDUZIDA, COD_GRADE, COD_FORNEC, DT_ALTERACAO,          CLASSIFICACAO_FISCAL, ICMS_REDUCAO, LAVAGEM, ALVEJAMENTO, SECAGEM, PASSADORIA, LIMP_SECO, PAIS_ORIGEM, UTILIZA_NUM_SERIE, COD_REFER_CONSOL, SITUACAO_TRIBUTARIA, ECF,  COD_FISCAL, PRECO_CUSTO_MED, NCM,   ICMS_SUBST_ENTRADA, PRECO_CEF, COD_GENERO, SIMILAR_PAIS, ICMS_IMP_VENDA, GRAMATURA, COD_GRUPTRIB, PERC_TRIBUTO, MIN_A_PRODUZIR, UTILIZA_MAX_VENDA, COD_SEGMTO_ANT, COD_GRUPO_ANT, COD_SUBGRUPO_ANT, TIPO_PRODUTO, COD_FASEPROD, ESTOQUE_RESERVADO, ESTOQUE_SEC3, ESTOQUE_SEC4, PRECO_CUSTO_MED_DIG, UNIDADE_MEDIDA_CONSUMO, PERC_ADICIONAL_PROD, PRECO_CUSTO_MED_CEF, CEST, TOL_LARGURA_TECIDO, TOL_GRAMATURA, TOL_RENDIMENTO, ALT_DIMENS_LAV_COMP, ALT_DIMENS_LAV_LARG, TORCAO_LAV, SOLIDEZ_LAV, PESO_APROX_ROLO, LIM_ACEITE_QUALIDADE, SOLIDEZ_FRIC_SECO_UMI, ESTOQUE_RESERVADO_BALCAB, CSOSN, COD_TIPO_REFER, TEMPO_OPERACIONAL_PADRAO, VR_MAO_DE_OBRA_PADRAO, FCP, ESTAB_ORIGEM, PASTA_IMAGEM, TIPO_GRADE, ID_PRODUTO_VNDA, DIMENSAO_ALTURA, DIMENSAO_LARGURA, DIMENSAO_COMPRIMENTO, ID_PRODUTO_IRROBA)

with cte_teste as (
select 5 quantidade, 'corrente ponto luz' descricao, 27 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'corrente 45cm' descricao, 91 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 3 quantidade, 'corrente nylon' descricao, 22 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'corrente 45cm' descricao, 145 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'corrente trevo 60cm' descricao, 210 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'corrente laminada 40cm' descricao, 22 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'corrente cruz n. s. aparecida' descricao, 80 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 2 quantidade, 'corrente meninono/menina' descricao, 42 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 3 quantidade, 'conjunto brinco/colar' descricao, 45 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'conjunto brinco/colar coração' descricao, 57 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 9 quantidade, 'conjunto brinco/colar zirc.' descricao, 35 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'corrente laminada 40cm' descricao, 28 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 3 quantidade, 'pandoras crav.' descricao, 150 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'pandoras lisa' descricao, 125 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'tonoz. Indiana' descricao, 75 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'tonoz. Concha' descricao, 26 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'pulseira fem.' descricao, 75 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 2 quantidade, 'pulseira coração' descricao, 17 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 3 quantidade, 'trio brinco zirc.' descricao, 33 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'argola quadrada' descricao, 14 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'argola coração' descricao, 19 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'brinco verde crav.' descricao, 108 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'brinco coração c/ zirc.' descricao, 85 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'brinco fake' descricao, 55 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'anel são jorge ' descricao, 103 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 3 quantidade, 'anel meia aliança' descricao, 34 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 3 quantidade, 'anel aliança' descricao, 46 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 2 quantidade, 'anel corações' descricao, 37 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 1 quantidade, 'anel coração' descricao, 61 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE UNION 
select 2 quantidade, 'anel meia aliança' descricao, 38 valor_uni,  rdb$set_context('USER_TRANSACTION','SEQ',cast(coalesce(rdb$get_context('USER_TRANSACTION','SEQ'),0) as integer)+1) s, cast(rdb$get_context('USER_TRANSACTION','SEQ') as integer) + 282 g from RDB$DATABASE
)
--COD_REFER, COD_SEGMTO, COD_GRUPO, COD_SUBGRUPO, COD_REFER_FORNEC, DESCRICAO,          COMPLEMENTO_DESCRICAO,  UNIDADE_MEDIDA_ENTD, UNIDADE_MEDIDA, FATOR_CONV_UNIDADE_MEDIDA, DT_INCLUSAO,            DT_CANCELAMENTO, DT_INI_BLOQUEIO,   DT_FIM_BLOQUEIO,   PRECO_CUSTO,                                     PRECO_CUSTO_ANT1, PRECO_CUSTO_ANT2, DT_PRECO_CUSTO, DT_CUSTO_ANT1,  DT_CUSTO_ANT2, PRECO_VENDA,                                                 ALIQUOTA_IPI, ESTOQUE_MINIMO, ESTOQUE_ATUAL, ESTOQUE_PENDENTE, ESTOQUE_PENDENTE_VENDA, ESTOQUE_FISCAL, ESTOQUE_SEC1, ESTOQUE_SEC2, PESO_LIQUIDO, PESO_BRUTO, COMISSAO_VENDA, MARGEM_LUCRO, COEFICIENTE_VENDA,                                                                                           DESPESAS_OPERACIONAIS, ICMS_SUBST, STATUS, COMISSAO_CUSTO, DESCONTO_LIMITADO, DESCONTO_MAXIMO, PRECO_VENDA_ANT1, DT_PRECO_VENDA, DT_VENDA_ANT1, ICMS_VENDA, IMPOSTO_FIXO, ORIGEM_INC, LARGURA_TECIDO, RENDIMENTO_TECIDO, DT_EXPIRACAO, DESCRICAO_CLASSE, COD_GRADE1, COD_GRADE2, COD_GRADE3, DESCRICAO_REDUZIDA, COD_GRADE, COD_FORNEC, DT_ALTERACAO,          CLASSIFICACAO_FISCAL, ICMS_REDUCAO, LAVAGEM, ALVEJAMENTO, SECAGEM, PASSADORIA, LIMP_SECO, PAIS_ORIGEM, UTILIZA_NUM_SERIE, COD_REFER_CONSOL, SITUACAO_TRIBUTARIA, ECF,  COD_FISCAL, PRECO_CUSTO_MED, NCM,   ICMS_SUBST_ENTRADA, PRECO_CEF, COD_GENERO, SIMILAR_PAIS, ICMS_IMP_VENDA, GRAMATURA, COD_GRUPTRIB, PERC_TRIBUTO, MIN_A_PRODUZIR, UTILIZA_MAX_VENDA, COD_SEGMTO_ANT, COD_GRUPO_ANT, COD_SUBGRUPO_ANT, TIPO_PRODUTO, COD_FASEPROD, ESTOQUE_RESERVADO, ESTOQUE_SEC3, ESTOQUE_SEC4, PRECO_CUSTO_MED_DIG, UNIDADE_MEDIDA_CONSUMO, PERC_ADICIONAL_PROD, PRECO_CUSTO_MED_CEF, CEST, TOL_LARGURA_TECIDO, TOL_GRAMATURA, TOL_RENDIMENTO, ALT_DIMENS_LAV_COMP, ALT_DIMENS_LAV_LARG, TORCAO_LAV, SOLIDEZ_LAV, PESO_APROX_ROLO, LIM_ACEITE_QUALIDADE, SOLIDEZ_FRIC_SECO_UMI, ESTOQUE_RESERVADO_BALCAB, CSOSN, COD_TIPO_REFER, TEMPO_OPERACIONAL_PADRAO, VR_MAO_DE_OBRA_PADRAO, FCP, ESTAB_ORIGEM, PASTA_IMAGEM, TIPO_GRADE, ID_PRODUTO_VNDA, DIMENSAO_ALTURA, DIMENSAO_LARGURA, DIMENSAO_COMPRIMENTO, ID_PRODUTO_IRROBA
select
   --rdb$db_key as row_number,
  c.g Codigo,     3,          1,         2,       '.',         upper(c.descricao),        NULL,                   'UND',               'UND',          1,                         '2024-08-31 00:00:00',  NULL,            NULL,              NULL,              CAST(replace(c.valor_uni,',','.') AS float), NULL,             NULL,             NULL,           NULL,           NULL,          CAST(replace(c.valor_uni,',','.') AS float),    0,            NULL,           NULL,          NULL,             NULL,                   NULL,           NULL,         NULL,         NULL,         NULL,       NULL,           0,            CAST(replace(c.valor_uni,',','.') AS float),  0,                     0,          '',     0,              NULL,              NULL,            NULL,             NULL,           NULL,          0,          0,            NULL,       NULL,           NULL,              NULL,         NULL,             NULL,       NULL,       NULL,       upper(c.descricao),    NULL,      NULL,       '2024-09-01 00:00:00', NULL,                 0,            0,       0,           0,       0,          0,         NULL,        NULL,              NULL,             '060',               NULL, c.g Codigo,          NULL,           null NCM, NULL,               NULL,      NULL,       NULL,         NULL,           NULL,      NULL,         NULL,         NULL,           'N',               NULL,           NULL,          NULL,             NULL,         NULL,         NULL,              NULL,         NULL,         NULL,                'UND',                  NULL,                NULL,                NULL, NULL,               NULL,          NULL,           NULL,                NULL,                NULL,       NULL,        NULL,            NULL,                 NULL,                  NULL,                     NULL,  1,              NULL, NULL, NULL, '', NULL, NULL, NULL, NULL, NULL, NULL, NULL
--*
from cte_teste c
where 1=1  and  c.s >=0
order by c.g
--and not exists(select * from refer r1 where r1.cod_refer=c.codigo)

--select c.valor from config c  where c.chave like 'ULT_CODFISCAL'
update
config c
set c.valor =(select max(r.cod_fiscal) from refer r)
where c.chave like 'ULT_CODFISCAL'
--select cod_refer,cod_fiscal from refer
--update refer r set r.cod_fiscal = cast(r.cod_refer as integer)
--where r.cod_refer <> cast(r.cod_fiscal as varchar(20)) and r.cod_refer > '252'
--and r.COD_SEGMTO=3



